---
- hosts: backend_summ
  become: yes
  remote_user: root
  gather_facts: false


  vars:
    project_source: /home/hex/mts_test/stage_2/backend_summ


  tasks:

    - name: Check python
      raw: test -e /usr/bin/python
      failed_when: false
      changed_when: false
      register: check_python

    - name: Install python
      raw: apk update && apk add python3
      when: check_python.rc != 0

    - name: Install apache2 and php
      apk:
        update_cache: true
        state: present
        name: php81, apache2, php81-apache2

    - name: Copy calc.php script
      copy:
        src: "{{ project_source }}/calc.php"
        dest: /var/www/localhost/htdocs/calc.php

    - name: Run apache2
      shell:
        cmd: pgrep httpd || httpd -BACKGROUND
      changed_when: false

