---
- hosts: mts_stage2
  become: yes
  remote_user: root
  gather_facts: false

  tasks:

    - name: Check python
      raw: test -e /usr/bin/python
      failed_when: false
      changed_when: false
      register: check_python

    - name: Install python
      raw: apk update && apk add python3
      when: check_python.rc != 0

